ARG base_image=aclemons/slackware:14.2_x86_64_latest
FROM $base_image

ARG base_image
RUN echo "Using base image $base_image"

COPY scripts/install_slackrepo.sh /
RUN bash /install_slackrepo.sh
RUN rm /install_slackrepo.sh
