---
name: Slackware 9.1 Docker Images

"on":
  schedule:
    - cron: '0 3 * * *'
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - name: Fetch x86 ChangeLogs
        run: |
          mkdir -p slackware-9.1
          curl -s -f -o slackware-9.1/ChangeLog.txt.386 https://slackware.osuosl.org/slackware-9.1/ChangeLog.txt

      - name: Cache Base Tarballs
        id: cache-base-tarballs
        uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3.3.1
        with:
          path: base_tarballs/
          key: ${{ runner.os }}-base-tarballs-9.1-${{ hashFiles('**/slackware-9.1/ChangeLog*', '**/scripts/build_base_image.sh') }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@2b82ce82d56a2a04d2637cd93a637ae1b359c0a7 # v2.2.0

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@ecf95283f03858871ff00b787d79c419715afc34 # v2.7.0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc # v2.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Login to DockerHub
        uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc # v2.2.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build prerequisites
        if: steps.cache-base-tarballs.outputs.cache-hit != 'true'
        run: |
          docker run --privileged --security-opt apparmor:unconfined --rm -e RELEASENAME=slackware -e ARCH=i586 -e VERSION=9.1 -e CHOWN_TO="$(id -u):$(id -g)" -v "$(pwd):/data" -v "$(pwd)/scripts:/scripts" alpine:3.15 sh /scripts/build_base_image.sh
          cp *.tar base_tarballs/

      - name: Restore prerequisites
        if: steps.cache-base-tarballs.outputs.cache-hit == 'true'
        run: |
          cp base_tarballs/*tar .

      - name: Build and push
        uses: docker/build-push-action@2eb1c1961a95fc15694676618e422e8ba1d63825 # v4.1.1
        with:
          push: true
          platforms: linux/386
          cache-from: type=gha
          cache-to: type=gha,mode=max
          context: .
          file: Dockerfile
          build-args: |
            VERSION=9.1
          tags: |
            ghcr.io/${{ github.repository_owner }}/slackware:9.1
            ${{ github.repository_owner }}/slackware:9.1
