name: Mirror Sync

on:
  workflow_dispatch:
  push:

permissions: {}

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  codeberg:
    name: Mirror to Codeberg
    runs-on: ubuntu-slim
    environment: codeberg-mirror
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          fetch-depth: 0
          show-progress: false
          persist-credentials: false

      - name: Mirror to codeberg
        env:
          CODEBERG_TOKEN: ${{ secrets.CODEBERG_TOKEN }}
          REPO_OWNER: ${{ github.repository_owner }}
          REPO: ${{ github.repository }}
        run: |
          git remote add mirror "https://$REPO_OWNER:$CODEBERG_TOKEN@codeberg.org/$REPO.git"
          git push --tags --force --prune mirror "refs/remotes/origin/*:refs/heads/*"
          git remote remove mirror
